# Project Name
site_name: "Chatrix.One XMPP Server | Документация"
site_description: >-
  Български XMPP сървър за свободна комуникация без телеметрия и реклами!
  Chatrix.One - Skip the Tracking, Keep the Chatting!

# Repository
# repo_url: https://github.com/ChatrixOne/docs.chatrix.one
# repo_name: ChatrixOne/docs.chatrix.one
# edit_uri: 'docs/'

# Theme Configuration
theme:
  name: material
  language: bg
  favicon: resources/favicon/favicon.png
  custom_dir: overrides
  font: false
  icon:
    logo: material/book-open-page-variant
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss
  # - content.action.edit
  # - content.action.view
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Тъмна тема
      primary: blue grey
      accent: teal
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Светла тема
      primary: blue grey
      accent: teal

# Customization
extra:
  social:
    - icon: fontawesome/solid/earth-americas
      link: https://chatrix.one
    - icon: fontawesome/brands/github
      link: https://github.com/ChatrixOne
    - icon: fontawesome/solid/comment-dots
      link: xmpp:admin@chatrix.one
    - icon: fontawesome/solid/envelope
      link: mailto:admin@chatrix.one
  # consent:
  #   title: Съгласие за използване на бисквитки
  #   description: >-
  #     Използваме "бисквитки", за да разпознаваме повторните Ви посещения и предпочитания, както и
  #     за измерване на ефективността на нашата документация и дали потребителите намират това,
  #     което търсят. С Вашето съгласие ни помагате да направим документацията си по-добра.
  #   cookies:
  #     analytics:
  #       name: Google Analytics
  #       checked: false
  #   actions:
  #    - accept
  #     - manage
  #     - reject
  generator: false

# Extra CSS code
extra_css:
  - stylesheets/extra.css

# Theme Extensions
markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Page tree
nav:
  - Начало: 'index.md'
  - Профил:
    - Регистрация: 'account/registration.md'
    - Форма за регистрация: 'account/registration-form.md'
    - Смяна на парола: 'account/change-password.md'
    - Дерегистрация: 'account/delete-account.md'
  - Клиенти: 'clients.md'
  - ЧЗВ: 'faq.md'
  - Условия: 'terms.md'
  - Поверителност: 'privacy.md'
  - Статус: 'status.md'
  - Блог: 'blog.md'
  - За Мен: 'about.md'

# Plugins
plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: false
      languages:
        - locale: bg
          default: true
          name: Български
          build: true
          site_name: "Chatrix.One XMPP Server | Документация"
        - locale: en
          name: English
          build: true
          site_name: "Chatrix.One | Documentation"
          default: false
          nav_translations:
            Дерегистрация: Unregister Account
            За Мен: About
            Клиенти: Clients
            Начало: Home
            Поверителност: Privacy
            Профил: Account
            Регистрация: Account Registration
            Смяна на парола: Change Password
            Статус: Status
            Блог: Blog
            Условия: Terms
            Форма за регистрация: Registration Form
            ЧЗВ: FAQ
  - git-revision-date-localized:
      type: date
# - glightbox
# - tags

# Footer Copyright
copyright: |
  &copy; 2018 - <script>document.write(new Date().getFullYear())</script> <a href="https://github.com/ChatrixOne"  target="_blank" rel="noopener"><b>Chatrix.One </b></a>This website does not use any cookies or tracking mechanisms and is made with ❤ in Sofia.