# Project Name
site_name: "Chatrix.One | Документация"

# Repository
# repo_url: https://github.com/ChatrixOne/docs.chatrix.one
# repo_name: ChatrixOne/docs.chatrix.one

# Theme Configuration
theme:
  icon:
    logo: material/book-open-page-variant
  favicon: resources/favicon/favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: bg
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Тъмна тема
      primary: blue grey
      accent: teal
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Светла тема
      primary: blue grey
      accent: teal

# Customization
extra:
  social:
    - icon: fontawesome/solid/earth-americas
      link: https://chatrix.one
    - icon: fontawesome/brands/github
      link: https://github.com/ChatrixOne
    - icon: fontawesome/solid/comment-dots
      link: xmpp:admin@chatrix.one
    - icon: fontawesome/solid/envelope
      link: mailto:admin@chatrix.one
  generator: false

# Extra CSS code
extra_css:
  - stylesheets/extra.css

# Theme Extensions
markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
# plugins:
#   - glightbox

# Page tree
nav:
  - Начало: 'index.md'
  - Регистрация: 'регистрация.md'
  - Клиенти: 'клиенти.md'
  - ЧЗВ: 'често-задавани-въпроси.md'
  - Правила: 'правила.md'
  - Поверителност: 'поверителност.md'
  - Статус: 'статус.md'
  - За Мен: 'за-мен.md'

# Footer Copyright
copyright: |
  &copy; <script>document.write(new Date().getFullYear())</script> <a href="https://github.com/ChatrixOne"  target="_blank" rel="noopener">Chatrix.One - Всички права запазени.</a>
